### PR TITLE
Adds CODEOWNER file

### PR DESCRIPTION
**Pull request by SternXD**
All this does is add the CODEOWNERS file for all the project maintainers I made a PR because it gave me a scary red button when trying to do it directly

### CODE REVIEW

**Review by junepark678 — CHANGES_REQUESTED** [review]
make it not red pls

**Review by WesleyBryie — COMMENTED** [review]
lgtm

**Review by junepark678 — CHANGES_REQUESTED** [review]
the tests are failing, therefore cannot merged

**Comment by SternXD** [comment]
CI Has been broke for a long time all this Pull Request adds is a codeowner file to .github/

**Pull request merged**
